services:
  api:
    container_name: docker-ui-api
    image: docker-ui/api:latest 
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    ports:
    # host:container
      - "7000:${PORT:-4000}"
    environment:
      - PORT=4000
      - NODE_ENV=production
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    user: root

  web:
    container_name: docker-ui-web
    image: docker-ui/web:latest 
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL : http://localhost:7000
    restart: always
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
  